// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4fP0qVt7FDZbbhcGbTfAooYcXWrJnkg0',
    appId: '1:2073437771:web:dea6102083d8d7d2e84fce',
    messagingSenderId: '2073437771',
    projectId: 'login-6d41a',
    authDomain: 'login-6d41a.firebaseapp.com',
    storageBucket: 'login-6d41a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADf4emIAuMHUP0ZRLXLOl9bgXON0kuAP8',
    appId: '1:2073437771:android:0ef8e18c95da61afe84fce',
    messagingSenderId: '2073437771',
    projectId: 'login-6d41a',
    storageBucket: 'login-6d41a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-DCOI7bw4rGEMFsGZSoeOj0UFgnw8VHo',
    appId: '1:2073437771:ios:50df432777337e9ae84fce',
    messagingSenderId: '2073437771',
    projectId: 'login-6d41a',
    storageBucket: 'login-6d41a.appspot.com',
    iosClientId: '2073437771-7lj3pullsep8uqobm10ipgt57rlg5d41.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-DCOI7bw4rGEMFsGZSoeOj0UFgnw8VHo',
    appId: '1:2073437771:ios:64c16bc22283a6c3e84fce',
    messagingSenderId: '2073437771',
    projectId: 'login-6d41a',
    storageBucket: 'login-6d41a.appspot.com',
    iosClientId: '2073437771-kvdqqr5klgnkdu61j7kac62v955t1q3k.apps.googleusercontent.com',
    iosBundleId: 'com.example.login.RunnerTests',
  );
}
